### ISSUE TITLE
Passing Database config settings

### ISSUE THREAD

**Issue by rohmulan** [jquery/themeroller.css-chassis.com#11]
Discuss ways to provide database config to the api. We have following options "
1. config in package.json
2. directly variables in .npmrc
3. A separate config file for database settings

I am more inclined towards third option as of now.

**Comment by jzaefferer** [comment]
Options 1. and 2. aren't exclusive, they're part of configuring an application through env vars. See also http://12factor.net/config

In other words, you shouldn't have any files commited to the git repository that contain database settings. Env vars are a good mechanism to accomplish that.

For config keys with machine-independent default values, you can use `package.json`'s `config` key. Though you could put placeholders there for the DB, e.g. `"db_host": "OVERRIDE ME"`

**Comment by rohmulan** [comment]
Closing this, we have decided to not use database atleast for this summer.
