### ISSUE TITLE
Decide API Specifications and Tools

### ISSUE THREAD

**Issue by rohmulan** [jquery/themeroller.css-chassis.com#2]
Decide upon tools and technologies to use and how the api looks to clients. Also decide upon the features the api is going to support

**Comment by arthurvr** [comment]
> Decide upon tools and technologies to use

I think we already decided on express or was that just for the demo?

**Comment by rohmulan** [comment]
yes, I'll close the issue

We will be using Express with mysql and our api will use POST.

**Comment by jzaefferer** [comment]
Are the API endpoints specified somewhere? I'm wondering what the POST is for.

**Comment by rohmulan** [comment]
@jzaefferer I plan to start a separate issue of it later, I think we are going to have a basic environment, and then start working on ui diretly until css-chassis is ready, and then go back to API so it wasn't on my list so far.
