### ISSUE TITLE
Choosing a Color Picker

### ISSUE THREAD

**Issue by rohmulan** [jquery/themeroller.css-chassis.com#5]
Need to decide from options available, a colorpicker to use in themeroller while choosing color.
Options are:
1. ~~HTML 5 color input~~ (Poor Browser Support)
2. [jquery-color-picker](http://www.eyecon.ro/colorpicker/)
3. [Farbtastic](http://acko.net/blog/farbtastic-jquery-color-picker-plug-in/)
And there's a bundle of other optons here: http://www.jqueryrain.com/demo/jquery-color-picker/

**We agreed upon using  [jquery-color-picker](http://www.eyecon.ro/colorpicker/)**

**Comment by arschmitz** [comment]
HTML 5 color input does not have enough support its not available in many of our supported browsers.

**Comment by sfrisk** [comment]
The jquery-color-picker doesn't look too bad, and allows people to use values they might get from a photoshop file.

**Comment by arthurvr** [comment]
I only had good experiences with [spectrum](http://bgrins.github.io/spectrum/) but it doesn't really look fancy (out of the box at least)
