### ISSUE TITLE
Database schema (mysql)

### ISSUE THREAD

**Issue by rohmulan** [jquery/themeroller.css-chassis.com#7]
Decide a database schema to use.

I am  currently considering something like this : 

``` sql
create table theme (
    id int unsigned not null auto_increment,
    name varchar(50),
    data TEXT,
    keywords varchar(100),
    created TIMESTAMP DEFAULT 0 not null,
    updated TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
    primary key(id),
    index(name)
)
```

data will hold the full json data of theme stringified with a JSON.stringify

I would love suggestions/ better options on this

**Comment by aulvi** [comment]
Looks good, but would having a field for theme 'version' field make sense here?

**Comment by rohmulan** [comment]
Each theme will be saved here, on change to the theme the `data` column for the theme will be updated, I doubt we would need a version? 
But if we are thinking of saving version of the themeroller itself, as in time we may have multiple, that could be interesting.

**Comment by rohmulan** [comment]
@aulvi , we also need some opinion for type of column to use in case of `data`  which will contain a large json data , probably encoded using JSON.stringify.. number of variables can get seriously high with time

**Comment by jzaefferer** [comment]
Where does the data come from? Are these presets like the ones in the [jQuery UI Themeroller gallery](http://jqueryui.com/themeroller/)? Or user generated themes? In both cases, why do we need a SQL database to store them?

**Comment by rohmulan** [comment]
We decided to make all themes sharable by url, and since our themes can have a lot of variables (in 3 digits atleast) we decided to save in database instead of in a file. These are user generated themes.

**Comment by aulvi** [comment]
Regarding the type for the `data` field, I think `TEXT` would be fine. If we find ourselves tight for space, we can either increase the field size (`MEDIUMTEXT` etc) or use something like messagepack to compress the json objects before storage. I don't know how big these objects will be once serialized so I defer to you :smile:

**Comment by rohmulan** [comment]
Closing this, we have decided to not use database atleast for this summer, will reopen if we decide on using it later. Will depend on how we decide to implement #12

**Comment by jzaefferer** [comment]
Sounds good, it'll remove a lot of complexity for now.
